name: autoReportPeace

on:
  repository_dispatch:
    types: [morning]
  workflow_dispatch:
jobs:
  send_message:
    runs-on: ubuntu-latest
    name: GO!

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/checkout@v3
      - name: checkout
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: push
        run: pip install -r ./requirements.txt && python ./main.py

    env:
      STUDENT_ID : ${{ secrets.STUDENT_ID }}
      PASSWORD  : ${{ secrets.PASSWORD }}
      NAME  : ${{ secrets.NAME }}
      SCHOOL  : ${{ secrets.SCHOOL }}
      MAJOR : ${{ secrets.MAJOR }}
      TYPE  : ${{ secrets.TYPE }}
      PHONE : ${{ secrets.PHONE }}
      MASTER  : ${{ secrets.MASTER }}
      BUILDING  : ${{ secrets.BUILDING }}
      ROOM  : ${{ secrets.ROOM }}
      IF_WEPUSH: ${{ secrets.IF_WEPUSH }}
      APP_ID  : ${{ secrets.APP_ID }}
      APP_SECRET  : ${{ secrets.APP_SECRET }}